name: Draco Insights Dashboard Translations
on: pull_request
jobs:
  label:
    runs-on: ubuntu-latest
      steps:
      - uses: Brightspace/third-party-actions@actions/labeler
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
